# Generated by Django 3.0.8 on 2021-04-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_api', '0002_usercurrency_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('country_code', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=50)),
                ('currency_symbol', models.CharField(max_length=1)),
                ('thousand_delimiter', models.CharField(max_length=1)),
                ('cents_delimiter', models.CharField(max_length=1)),
                ('currency_identificator', models.CharField(max_length=10)),
                ('currency_identificator_position', models.CharField(max_length=10)),
                ('is_show_cents', models.BooleanField()),
            ],
        ),
    ]
