# Generated by Django 3.0.8 on 2021-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_api', '0003_currencyformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyformat',
            name='cents_delimiter',
            field=models.CharField(choices=[('.', '.'), (',', ',')], max_length=1),
        ),
        migrations.AlterField(
            model_name='currencyformat',
            name='currency_identificator',
            field=models.CharField(choices=[('CODE', 'CODE'), ('SYMBOL', 'SYMBOL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='currencyformat',
            name='currency_identificator_position',
            field=models.CharField(choices=[('BEOFRE', 'BEFORE'), ('AFTER', 'AFTER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='currencyformat',
            name='thousand_delimiter',
            field=models.CharField(choices=[('.', '.'), (',', ',')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='currencyformat',
            unique_together={('country_code', 'currency_code')},
        ),
    ]
