# Generated by Django 3.0.8 on 2021-04-03 19:08

import currency_api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_api', '0004_auto_20210403_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyformat',
            name='cents_delimiter',
            field=models.CharField(choices=[('.', '.'), (',', ',')], default='.', max_length=1),
        ),
        migrations.AlterField(
            model_name='currencyformat',
            name='currency_identificator',
            field=models.CharField(choices=[('CODE', 'CODE'), ('SYMBOL', 'SYMBOL')], default=currency_api.enums.CurrencyIdentificator['SYMBOL'], max_length=10),
        ),
        migrations.AlterField(
            model_name='currencyformat',
            name='currency_identificator_position',
            field=models.CharField(choices=[('BEOFRE', 'BEFORE'), ('AFTER', 'AFTER')], default='BEOFRE', max_length=10),
        ),
        migrations.AlterField(
            model_name='currencyformat',
            name='thousand_delimiter',
            field=models.CharField(choices=[('.', '.'), (',', ',')], default=',', max_length=1),
        ),
    ]
