# Generated by Django 3.0.8 on 2021-04-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_api', '0005_auto_20210403_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyformat',
            name='currency_identificator_position',
            field=models.CharField(choices=[('BEFORE', 'BEFORE'), ('AFTER', 'AFTER')], default='BEFORE', max_length=10),
        ),
    ]
