# Generated by Django 3.0.8 on 2021-04-04 06:08

import currency_api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_api', '0006_auto_20210404_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyformat',
            name='cents_delimiter',
            field=models.CharField(choices=[('.', '.'), (',', ',')], default=currency_api.enums.CurrencyDelimitor['DOT'], max_length=1),
        ),
        migrations.AlterField(
            model_name='currencyformat',
            name='currency_identificator_position',
            field=models.CharField(choices=[('BEFORE', 'BEFORE'), ('AFTER', 'AFTER')], default=currency_api.enums.CurrencyIdentificatorPosition['BEFORE'], max_length=10),
        ),
        migrations.AlterField(
            model_name='currencyformat',
            name='thousand_delimiter',
            field=models.CharField(choices=[('.', '.'), (',', ',')], default=currency_api.enums.CurrencyDelimitor['COMMA'], max_length=1),
        ),
    ]
